package br.edu.unifei.trabalho;

public class App {

	public static void main(String[] args) {
		Arma a = new Arma();
		a.setNome("vandal");
		a.setDano(150);
		a.setQuantidadeBalas(24);
		
		Agente ag1 = new Agente();
		Agente ag2 = new Agente();
		Agente ag3 = new Agente();
		Agente ag4 = new Agente();
		Agente ag5 = new Agente();
		ag1.setNome("Raze");
		ag1.setClasse("Duelista");
		Dano d = new Dano();
		d.setQuantidadeDano(80);
		Estado e = new Disponivel();
		SemRecarga h = new SemRecarga(d);
		h.setQuantiaUtilizavel(1);
		h.setNome("Cartucho de tinta");
		h.setEstado(e);
		ag1.getHabilidades().add(h);
		ag2.setNome("Sage");
		ag2.setClasse("Sentinela");
		Suporte s = new Suporte();
		s.setEfeito("Cura");
		s.setDuracaoEfeito(5);
		RecargaTempo h2 = new RecargaTempo(s);
		h2.setTempoRecarga(30);
		h2.setNome("Orbe de Cura");
		h2.setEstado(e);
		ag2.getHabilidades().add(h2);
		ag3.setNome("Skye");
		ag3.setClasse("Iniciador");
		s.setDuracaoEfeito(6);
		RecargaTempo h3 = new RecargaTempo(s);
		h3.setEstado(e);
		ag3.getHabilidades().add(h3);
		ag4.setNome("Viper");
		ag4.setClasse("Controlador");
		s.setEfeito("Smoke");
		s.setDuracaoEfeito(7);
		RecargaTempo h4 = new RecargaTempo(s);
		h4.setEstado(e);
		ag4.getHabilidades().add(h4);
		ag5.setNome("Omen");
		ag5.setClasse("Controlador");
		s.setEfeito("Smoke");
		s.setDuracaoEfeito(7);
		RecargaTempo h5 = new RecargaTempo(s);
		ag5.getHabilidades().add(h5);
		h5.setEstado(e);
		e.inverter(h5);
		
		Jogador j1 = new Jogador();
		Jogador j2 = new Jogador();
		Jogador j3 = new Jogador();
		Jogador j4 = new Jogador();
		Jogador j5 = new Jogador();
		j1.setNome("Xand");
		j1.setAgente(ag1);
		j1.setArma(a);
		j1.setNacionalidade("brasileiro");
		j2.setNome("Jonn");
		j2.setAgente(ag2);
		j2.setArma(a);
		j2.setNacionalidade("brasileiro");
		j3.setNome("Caua");
		j3.setAgente(ag3);
		j3.setArma(a);
		j3.setNacionalidade("brasileiro");
		j4.setNome("Vixen");
		j4.setAgente(ag4);
		j4.setArma(a);
		j4.setNacionalidade("brasileiro");
		j5.setNome("bzn");
		j5.setAgente(ag5);
		j5.setArma(a);
		j5.setNacionalidade("brasileiro");
		Time t = new Time();
		t.setNome("Nip");
		t.getJogadores().add(j1);
		t.getJogadores().add(j2);
		t.getJogadores().add(j3);
		t.getJogadores().add(j4);
		t.getJogadores().add(j5);
		
		Jogador j6 = new Jogador();
		Jogador j7 = new Jogador();
		Jogador j8 = new Jogador();
		Jogador j9 = new Jogador();
		Jogador j10 = new Jogador();
		j6.setNome("Aspas");
		j6.setAgente(ag1);
		j6.setArma(a);
		j6.setNacionalidade("brasileiro");
		j7.setNome("Saadhack");
		j7.setAgente(ag2);
		j7.setArma(a);
		j7.setNacionalidade("argentino");
		j8.setNome("Sacy");
		j8.setAgente(ag3);
		j8.setArma(a);
		j8.setNacionalidade("brasileiro");
		j9.setNome("Less");
		j9.setAgente(ag4);
		j9.setArma(a);
		j9.setNacionalidade("brasileiro");
		j10.setNome("Pancada");
		j10.setAgente(ag5);
		j10.setArma(a);
		j10.setNacionalidade("brasileiro");
		Time t2 = new Time();
		t2.setNome("Loud");
		t2.getJogadores().add(j6);
		t2.getJogadores().add(j7);
		t2.getJogadores().add(j8);
		t2.getJogadores().add(j9);
		t2.getJogadores().add(j10);
		Partida p = new Partida(t,t2);
		p.setQuantidadeRodadas(28);
		p.setVencedor(t2);
		Mapa m = new Mapa();
		m.setNome("Ascent");
		m.setPartida(p);
		p.setMapa(m);
		Nacional n = new Nacional();
		n.setLocomocao(1000);
		n.setRegiao("Rio de Janeiro");
		MataMata c = new MataMata(n);
		c.setApresentador("Guilherme Spacca");
		c.setCanalTransmissao("VALORANT_BR");
		c.getPartidas().add(p);
		c.getTimes().add(t);
		c.getTimes().add(t2);
		c.setCampeao(t2);
		
		System.out.println("Os jogadores da equipe "+ t.getNome() +" sao:");
		System.out.println(j1.getNome() + ", " + j2.getNome() + ", " + j3.getNome() + ", " +j4.getNome()+ ", "+j5.getNome());
		System.out.println("Os jogadores da equipe "+ t2.getNome() +" sao:");
		System.out.println(j6.getNome() + ", " + j7.getNome() + ", " + j8.getNome() + ", " +j9.getNome()+ ", "+j10.getNome());
		System.out.println("Os agentes escolhidos por ambos os times foram: ");
		System.out.println(ag1.getNome() + ", " + ag2.getNome() + ", " + ag3.getNome() + ", " +ag4.getNome()+ ", "+ag5.getNome()+"\n");
		
		System.out.println("Os custos do campeonato foram: " + c.custos());
		System.out.println("O campeonato ocorreu em " + n.getRegiao());
		System.out.println("O campeonato foi apresentado por: " + c.getApresentador());
		System.out.println("A partida ocorreu no mapa: " + m.getNome());
		System.out.println("A partida durou " + p.getQuantidadeRodadas()+ " rodadas \n");
		System.out.println("O campeao do torneio foi o time: " + c.getCampeao().getNome());
	}

}
